[build]
  publish = "dist"
  command = "npm run build"
  # Updated configuration for backend redirect

[[redirects]]
  from = "/api/*"
  to = "https://mongodb-rag-atlas-vector-search.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
