[build]
  publish = "dist"
  command = "npm run build"
  # Updated configuration for backend redirect

[[redirects]]
  from = "/api/*"
  to = "https://markdk-rag-backend.hf.space/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
